#!/bin/sh

set -ex

export NODE_VERSION=6.10.3
export SHA256=00d0aea8e47a68da6e3278d7c2fc1504de46a34d97b4b2fa5610b04a64fce04c

DIR="$( cd "$( dirname "$0" )" && pwd )"

cd "${DIR}/.."

docker-compose build
docker-compose run --rm \
  -e NODE_VERSION -e SHA256 \
  package
